### PR TITLE
Added appveyor control file.

### PR DESCRIPTION
**Pull request by kf6kjg**
Just adding AppVeyor, not yet cleaning up the folder structure.

### CODE REVIEW

**Comment by kf6kjg** [comment]
Looks like I'll need to do a little cleanup in VS to make sure the project file handles the x64 mode.

**Review by appurist — APPROVED** [review]
I don't know AppVeyor too well but this is a fairly simple project, but I've reviewed the file and see no obvious issues. Also, there is no risk in adding a new file here, as we move forward with automation.

Note that the project itself is incomplete, it does not implement AIS yet. It provides hooks for the front (REST) and back (inventory) ends without the logic linking the two parts. But this is a step forward that I'm pleased to see.

**Comment by appurist** [comment]
Hmm, on a closer second look, it seems the project platform was changed from `AnyCPU` to `x64`. While we may be expecting x64, this may trigger incompatibilities or warnings when mixing with `AnyCPU` DLLs, does it not? Was this change intentional or accidental from VS updates?

**Comment by kf6kjg** [comment]
It was purposeful: no more valid reason than that I'm setting everything in Halcyon to x64 only.

I've not seen any issues, but I know little about this project ATM: hence asking your review.

**Comment by appurist** [comment]
Okay. The thing about `AnyCPU` is that it allows DLLs to be loaded into any host process environment, i.e. you can load it into an EXE process that was started as a 32-bit app. Setting it to `x64` just limits it to 64-bit only, so the DLL can't be loaded in that case. 

This isn't likely to be a problem in most builds (and _won't_ be a problem if it's building an EXE), but in general this is a limitation we wouldn't want in an open-source project. For example: the latest (and last) _Linux User and Developer_ magazine has an article on building and loading .NET Core applications on a Raspberry Pi. (Stop laughing, it's serious apps!) 😆 I have several small ODROID boxes (similar to Pi), running Linux, and while they aren't too capable, it might be suitable for central grid services, or AIS.

For libraries, we almost certainly don't want to just arbitrarily limit it to 64-bit executable builds (or anything specific).  One of the nice things about .NET is the platform independence.  For executables, we could.  I just don't really see what the benefit of _preventing_ it from running on some machines would be here, especially given the hobbyist nature of the open-source Halcyon projects.

**Comment by kf6kjg** [comment]
As said in another project I'll be revisiting the whole AnyCPU thing.  Thank you for the clarity.

**Pull request merged**
